import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cryptoweb - for all your digital curruncy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h4 className="text-3xl font-bold">Hello world!</h4>
    </div>
  );
}
