import Head from "next/head";
import Layout from "../components/Layout/layout";
import Currency from "../components/sections/Currency";
import Hero from "../components/sections/Hero";
import Trade from "../components/sections/Trade";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cryptoweb - for all your digital curruncy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Hero />
        <Currency />
        <Trade />
      </Layout>
    </div>
  );
}
