import Head from "next/head";
import Layout from "../components/Layout/layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cryptoweb - for all your digital curruncy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section>
          
        </section>
      </Layout>
    </div>
  );
}
